# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publisher.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpublisher.proto\"0\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"%\n\x0fPublishResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x32@\n\tPublisher\x12\x33\n\x0ePublishMessage\x12\x0f.PublishRequest\x1a\x10.PublishResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'publisher_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PUBLISHREQUEST']._serialized_start=19
  _globals['_PUBLISHREQUEST']._serialized_end=67
  _globals['_PUBLISHRESPONSE']._serialized_start=69
  _globals['_PUBLISHRESPONSE']._serialized_end=106
  _globals['_PUBLISHER']._serialized_start=108
  _globals['_PUBLISHER']._serialized_end=172
# @@protoc_insertion_point(module_scope)
