# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csender.proto\"-\n\x0bSendRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\"\n\x0cSendResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x32\x34\n\x06Sender\x12*\n\x0bSendMessage\x12\x0c.SendRequest\x1a\r.SendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sender_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SENDREQUEST']._serialized_start=16
  _globals['_SENDREQUEST']._serialized_end=61
  _globals['_SENDRESPONSE']._serialized_start=63
  _globals['_SENDRESPONSE']._serialized_end=97
  _globals['_SENDER']._serialized_start=99
  _globals['_SENDER']._serialized_end=151
# @@protoc_insertion_point(module_scope)
