# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscriber.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10subscriber.proto\"=\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\'\n\x11SubscribeResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x32@\n\nSubscriber\x12\x32\n\tSubscribe\x12\x11.SubscribeRequest\x1a\x12.SubscribeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subscriber_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=20
  _globals['_SUBSCRIBEREQUEST']._serialized_end=81
  _globals['_SUBSCRIBERESPONSE']._serialized_start=83
  _globals['_SUBSCRIBERESPONSE']._serialized_end=122
  _globals['_SUBSCRIBER']._serialized_start=124
  _globals['_SUBSCRIBER']._serialized_end=188
# @@protoc_insertion_point(module_scope)
